name: linter-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: lint-name
        run: make lint
